os:
  - windows
  - osx

language: rust

cache: cargo
#    directories:
#     - /home/travis/.cargo/

script:
  - source ci/env.sh
  - echo scripts/cargo-install-all.sh solana-release
  - ci/publish-tarball.sh

