os:
  - windows
  - osx

language: rust
cache: cargo
rust:
  - 1.35.0

install:
  - source ci/rust-version.sh
  - test $rust_stable = $TRAVIS_RUST_VERSION # Update .travis.yml rust version above when this fails

script:
  - source ci/env.sh
  - ci/publish-tarball.sh

