[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
version = "1.1.20"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bs58 = "0.3.0"
clap = "2.33.0"
histogram = "*"
log = { version = "0.4.8" }
serde_json = "1.0.48"
serde_yaml = "0.8.11"
solana-clap-utils = { path = "../clap-utils", version = "1.1.20" }
solana-cli = { path = "../cli", version = "1.1.20" }
solana-ledger = { path = "../ledger", version = "1.1.20" }
solana-logger = { path = "../logger", version = "1.1.20" }
solana-runtime = { path = "../runtime", version = "1.1.20" }
solana-sdk = { path = "../sdk", version = "1.1.20" }
solana-stake-program = { path = "../programs/stake", version = "1.1.20" }
solana-transaction-status = { path = "../transaction-status", version = "1.1.20" }
solana-vote-program = { path = "../programs/vote", version = "1.1.20" }
tempfile = "3.1.0"

flate2 = "1.0.14"
bincode = "1.2.1"
zstd = "0.5.1"
bzip2 = "0.3.3"
enum-iterator = "0.6.0"
serde = "1.0.112"
serde_derive = "1.0.103"

[dev-dependencies]
assert_cmd = "1.0"

[target."cfg(unix)".dependencies]
signal-hook = "0.1.15"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
